### ISSUE TITLE
[SOLVED] troubleshoot information

### ISSUE THREAD

**Issue by samundra** [foss-np/anubad-web#2]
At command

`pip install -r requirements.txt` I got following exceptions.

```
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 672, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 902, in move_wheel_files
    pycompile=self.pycompile,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 206, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 193, in clobber
    os.makedirs(destsubdir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/Babel-2.3.4.dist-info'

Storing debug log for failure in /home/developer/.pip/pip.log
```

to solve the problem, I had to run the above command with _sudo_ .

```
sudo pip install -r requirements.txt
```

**Comment by rupakraj** [comment]
Actually, if you work on the **virtual environment**, we don't need `sudo` for pip.
